<?php

define('PATH_CONFIG', PATH . 'Config' . DIRECTORY_SEPARATOR);
define('PATH_APP', PATH . 'App' . DIRECTORY_SEPARATOR);
define('PATH_FILE', PATH . 'File' . DIRECTORY_SEPARATOR);
define('PATH_MIGRATION', PATH . 'Migration' . DIRECTORY_SEPARATOR);
define('PATH_PUBLIC', PATH . 'Public' . DIRECTORY_SEPARATOR);
define('PATH_ROUTER', PATH . 'Router' . DIRECTORY_SEPARATOR);

define('PATH_APP_CONTROLLER', PATH_APP . 'Controller' . DIRECTORY_SEPARATOR);
define('PATH_APP_MIDDLEWARE', PATH_APP . 'Middleware' . DIRECTORY_SEPARATOR);
define('PATH_APP_MODEL', PATH_APP . 'Model' . DIRECTORY_SEPARATOR);
define('PATH_APP_VIEW', PATH_APP . 'View' . DIRECTORY_SEPARATOR);

define('PATH_FILE_CACHE', PATH_FILE . 'Cache' . DIRECTORY_SEPARATOR);
define('PATH_FILE_LOG', PATH_FILE . 'Log' . DIRECTORY_SEPARATOR);
define('PATH_FILE_TMP', PATH_FILE . 'Tmp' . DIRECTORY_SEPARATOR);

define('PATH_SYSTEM_CMD', PATH_SYSTEM . 'Cmd' . DIRECTORY_SEPARATOR);
